klp_mcp_server:
  enabled: true
  server:
    name: 'Simple MCP Server'
    version: '1.0.0'
  server_providers: ['streamable_http', 'sse']
  sse_adapter: 'cache'
  adapters:
    cache:
      prefix: 'mcp_sse_'
      ttl: 100
  tools:
    - App\Mcp\EchoTool
    - App\Mcp\TimeTool
    - App\Mcp\MeteoDataTool
    - App\Mcp\MeteoStationTool
